# Stunnel configuration for BMC0 to communicate with sibling BMC

provider = tpm2
provider = default
foreground = yes

socket = l:TCP_NODELAY=1
socket = r:TCP_NODELAY=1
OCSP = no
OCSPrequire = no
OCSPaia = no

debug = 7
output = /tmp/stunnel_bmc0.log

[sibling_bmc]
client = yes
accept = 127.0.0.1:1705
connect = <bmc1_ip>:5071
cert   = /etc/tpm-demo/certs/bmc0.crt
key    = handle:0x81000020
CAfile = /etc/tpm-demo/certs/cacert.pem
verify = 2
