# Stunnel configuration for BMC0 to communicate with sibling BMC

provider = tpm2
foreground = yes
socket = l:TCP_NODELAY=1
socket = r:TCP_NODELAY=1
OCSP = no
OCSPrequire = no
OCSPaia = no

debug = 7
output = /tmp/stunnel.log

[local_bmc]
client = no
accept = 5071
connect = 127.0.0.1:1705
cert   = handle:0x1500022
key    = handle:0x81000020
CAfile = /etc/tpm-demo/certs/cacert.pem
verify = 2

[sibling_bmc]
client = yes
accept = 127.0.0.1:1706
connect = <bmc1_ip>:6071
cert   = handle:0x1500022
key    = handle:0x81000020
CAfile = /etc/tpm-demo/certs/cacert.pem
verify = 2
