# Stunnel configuration for BMC1 to communicate with sibling BMC

provider = tpm2
foreground = yes

socket = l:TCP_NODELAY=1
socket = r:TCP_NODELAY=1
OCSP = no
OCSPrequire = no
OCSPaia = no
session = 0

debug = 7
output = /tmp/stunnel_bmc1.log

[local_bmc]
client = no
accept = 6071
connect = 127.0.0.1:1706
cert   = handle:0x1500032
key    = handle:0x81000021
CAfile = /etc/tpm-demo/certs/cacert.pem
verify = 2

[sibling_bmc]
client = yes
accept = 127.0.0.1:1705
connect = <bmc0_ip>:5071
cert   = handle:0x1500032
key    = handle:0x81000021
CAfile = /etc/tpm-demo/certs/cacert.pem
verify = 2