# Stunnel configuration for BMC1 to communicate with sibling BMC

provider = tpm2
provider = default
foreground = yes

socket = l:TCP_NODELAY=1
socket = r:TCP_NODELAY=1
OCSP = no
OCSPrequire = no
OCSPaia = no
session = 0

debug = 7
output = /tmp/stunnel_bmc1.log

[local_bmc]
client = no
accept = 5071
connect = 127.0.0.1:1705
cert   = /etc/tpm-demo/certs/bmc1.crt
key    = handle:0x81000021
CAfile = /etc/tpm-demo/certs/cacert.pem
verify = 2
