read only = yes
address = 127.0.0.1
port = 1706
log file = /dev/null

[bmc_fs]
    path = /
    read only = false
    uid = root
    gid = root

    # Exclude everything by default
    exclude = /**

    # Allow specific directories
    include = /tmp**